### ISSUE TITLE
Do you mind if modify for Paper server?

### ISSUE THREAD

**Issue by Chiharu-Hagihara** [sya-ri/EasySpigotAPI#1]
Do you mind if I modify this library for the Paper server?

**Comment by sya-ri** [comment]
Don't need to. This library feature is spigot(bukkit) only. We can use it as it as if we use it on Paper. 

p.s. The issue title was not good. So I changed.

**Comment by sya-ri** [comment]
If we use this library on forked Spigot, rewrite dependencies in build.gradle like this;

```build.gradle.kts

    dependencies {
        // ...
        implementation("com.github.sya-ri:EasySpigotAPI:1.0.0") {
                exclude(group = "org.spigotmc", module = "spigot-api")
        }
        implementation("net.pl3x.purpur:purpur-api:1.16.5-R0.1-SNAPSHOT") // e.g. Purpur
    }
```
