### ISSUE TITLE
config: sender 無しで読み込めるようにする

### ISSUE THREAD

**Issue by Chiharu-Hagihara** [sya-ri/EasySpigotAPI#45]
EasySpigotAPIたくさん使わせてもらっています！

ただ一つ使いにくいと思ったのがConfig読み込み時にCommandSenderが必須というところです。
起動時にConfigから読み込むときはコマンドを実行する必要があるのでこれをCommandSenderなしでできるようにしてほしいなと思いました。
可能であればお願いしますm(__)m

**Comment by sya-ri** [comment]
consoleSender を利用すればいい話ですが、対応します

追記: 対応しました。 2b85edd2b49ea48d9159c3810f14ef91cdd20ce2
