### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by kate-gg** [sya-ri/EasySpigotAPI#83]
I got this error on IntelliJ
```Cannot access class 'org.bukkit.command.CommandSender'. Check your module classpath for missing or conflicting dependencies```
and it's turn out to be error on every Bukkit & Spigot dependencies

**Comment by sya-ri** [comment]
It's a problem with your build script. Please see: https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:excluding-transitive-deps

The biggest problem is using implementation in my build script. If I use compileOnly instead, we won't have to specify exclude in the future. ~~It will be supported in the next version.~~ (new API: https://github.com/sya-ri/ktSpigot) Please exclude now.
